title:               Lara Mason
url:                 https://lhmason.github.io/blog
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Lara Mason
  url:               lhmason.github.io
  email:             lara@mason.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
